name: Terraform AWS Setup

on:
  workflow_dispatch:
    inputs:
        environment:
          description: "deploy environments"
          required: true
          default: dev
          type: choice
          options: 
            - dev
            - staging
            - prod
          
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main
permissions:
  id-token: write 

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
       fetch depth: 0
       ref: SSO
      # with:
      #     token: ${{ secrets.TOKEN }}
          
    - name: Configure Git
      run: |
        git config --global user.name 'kishorevr97'
        git config --global user.email 'kishorevr97@gmail.com'
    

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::084828605119:role/github-actions-kishore1
        role-session-name: samplerolesession
        aws-region: eu-north-1

    - name: Initialize Terraform
      run: |
        cd infrastructure/environment/${{ github.event.inputs.environment }}
        terraform init

    - name: Install & Configure TFLint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        tflint --init
         
    - name: validate tf configuration
      run: |
        tflint
      continue-on-error: true

    - name: Select Workspace
      run: terraform workspace select ${{ github.event.inputs.environment }} || terraform workspace new ${{ github.event.inputs.environment }}

    - name: Generate Terraform Plan
      run: |
        cd infrastructure/environment/${{ github.event.inputs.environment }}
        terraform plan '-var-file=${{ github.event.inputs.environment }}.tfvars' -out=tfplan

    # - name: install lfs
    #   run: |
    #      git lfs install
    #      git lfs track ".terraform/**/*"
    #      git add .gitattributes
    #      git commit -m "Add .terraform files to Git LFS"
    #      git push origin main

    - name: Install Terraform Docs
      if: github.event_name == 'pull_request'
      uses: terraform-docs/gh-actions@v1.3.0
      with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"

    - name: Terraform Apply 
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
      run: |
        cd infrastructure/environment/${{ github.event.inputs.environment }}
        terraform apply '-var-file=${{ github.event.inputs.environment }}.tfvars' -auto-approve
